#index:
#    path: /
#    controller: App\Controller\DefaultController::index
KunstmaanMultiDomainBundle:
  resource: "@KunstmaanMultiDomainBundle/Resources/config/routing.yml"
  requirements:
    _locale: "%requiredlocales%"
